# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10, verbose_name='\u4e3b\u9875\u56fe\u7247')),
                ('image', models.ImageField(default='', max_length=200, upload_to='home/%Y/%m', verbose_name='\u4e3b\u9875\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e3b\u9875\u56fe\u7247',
                'verbose_name_plural': '\u4e3b\u9875\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='RecommendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='\u63a8\u8350\u6587\u7ae0\u6807\u9898')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u63a8\u8350\u6587\u7ae0',
                'verbose_name_plural': '\u63a8\u8350\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='SentenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, verbose_name='\u6bcf\u65e5\u4e00\u53e5')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6bcf\u65e5\u4e00\u53e5',
                'verbose_name_plural': '\u6bcf\u65e5\u4e00\u53e5',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='title_image',
            field=models.ImageField(default='', max_length=200, upload_to='articles/%Y/%m', verbose_name='\u6807\u9898\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='recommendmodel',
            name='recommend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='personal_blog.ArticleModel', verbose_name='\u63a8\u8350\u6587\u7ae0'),
        ),
    ]
