# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_auto_20180328_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendmodel',
            name='title',
        ),
    ]
