# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0003_remove_recommendmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendmodel',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='\u63a8\u8350\u6587\u7ae0\u6807\u9898'),
        ),
    ]
