# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0008_noticemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title_image',
            field=models.ImageField(default='', max_length=200, upload_to='media/articles/%Y/%m', verbose_name='\u6807\u9898\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='homeimagemodel',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='media/home/%Y/%m', verbose_name='\u4e3b\u9875\u56fe\u7247'),
        ),
    ]
