# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 20:51
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0009_auto_20180328_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendmodel',
            name='recommend',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u63a8\u8350\u6587\u7ae0'),
        ),
    ]
